### ISSUE TITLE
pip install pykemon returns the v1client

### ISSUE THREAD

**Issue by bsushmith** [PokeAPI/pokepy#20]
Discrepancy between the readme and the pykemon version downloaded through pip
```python 
(venv)  ✝  ~  clear
(venv)  ✝  ~  pip install pykemon
(venv)  ✝  ~  python
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import pykemon
>>> client = pykemon.V2Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pykemon' has no attribute 'V2Client'
>>> client = pykemon.V1Client()
>>>

**Comment by Kronopt** [comment]
We have previously discussed asking @phalt for the pypi credentials in pull request #18 [here](https://github.com/PokeAPI/pykemon/pull/18#issuecomment-430535419), but that has not happened yet.

**Comment by Naramsim** [comment]
Maybe we could suggest in the readme to install from Github

```sh
pip install https://github.com/PokeAPI/pykemon/master.zip
```

I haven't tested it.

**Comment by Kronopt** [comment]
Yeah, it should work, as per the [pip readme](https://pip.pypa.io/en/stable/reference/pip_install/#git).

However, it would be better if the pypi package could be updated.
Is @phalt could help us out, that would be awesome.

We could also fork this into a completely new project, and get a new pypi page and all that

**Comment by Naramsim** [comment]
It is better to create a new Pypi project. @phalt cannot give us his account since it has other packages there. 

Maybe we can decide a new name too, instead of simply calling it `pykemon2`... (which is not a bad idea, anyway)

**Comment by Kronopt** [comment]
> The documentation also refers to the V1 usage.

Another thing I can't update without login credentials...

We will now discuss the forking of this project so that we can have control over things like the pypi and documentation pages.

I'll open another issue for this

**Comment by Kronopt** [comment]
@bsushmith, you put this whole thing on motion! 😅
You can now get pokepy 0.4.0 through pip:

```bash
pip install pykemon
````

Version 0.5.0, which allows caching, still needs further testing and won't be uploaded for now.
I'm sorry in advance for the documentation mentioning the caching feature already.

**Comment by tdmalone** [comment]
@kronopt I assume you meant pokepy in the pip command above?

**Comment by Kronopt** [comment]
Yeah, sorry!
