### ISSUE TITLE
pykemon fork

### ISSUE THREAD

**Issue by Kronopt** [PokeAPI/pokepy#21]
As mentioned in #20, we should fork pykemon so that we can have control over many aspects of the project only @phalt can, like pypi and readthedocs pages.

We should also give a new name to the project, like `pykemon2`, `pokeapi-py-wrapper`, `pypokeapi`, `pypoke`, or something along these lines.

@Naramsim, @tdmalone

**Comment by tdmalone** [comment]
Hi @Kronopt, is a fork necessary? @Naramsim and I now have access to most things @phalt set up, if there is additional stuff we forgot to ask him for can you list it in https://github.com/PokeAPI/pokeapi/wiki/PokeAPI-tools-&-accounts? I can then follow up with him by e-mail and get the access we need, and pass the relevant stuff along to you.

**Comment by Kronopt** [comment]
The only problems I have is not being able to update the **pypi page** and the **readthedocs documentation** page.
I could create new ones but with different names. That's one of the reasons for the fork.

For the pypi page, I don't know if it is possible to transfer it between accounts. One thing that I think could be done is for the page to be deleted and a new one created by an account controlled by the pokeapi team.

The readthedocs page could just be deleted and a new one created, I think.

What do you think? And, more importantly, what does @phalt think?

**Comment by Naramsim** [comment]
I wasn't thinking about forking Pykemon. We can still use this Github repo. I was just suggesting to create a new entry in Pypi and upload there the Pykemon package.

**Comment by Kronopt** [comment]
My bad.
But still, the name of the Github repo would still be different from the pypi page.

**Comment by tdmalone** [comment]
We can rename the Github repo if that's the easiest solution?

**Comment by Naramsim** [comment]
The easiest would be `Pykemon2`. 

@Kronopt, list your options since you are the maintainer 😄

**Comment by Kronopt** [comment]
Of the names myself and @Naramsim suggested:
* `pykemon2`
* `pokeapi-py-wrapper`
* `pypokeapi`
* `pypoke`
* `pokepy`

Of these, i prefer `pokepy`

**Comment by Kronopt** [comment]
Ok. I'll update the README soon.
As for the Pypi account, please inform me when you have one.
As for the docs, do enable the github pages!

**Comment by Kronopt** [comment]
You mean, having the documentation on a different branch altogether? Why not have it on the /docs folder in the master branch?

**Comment by Naramsim** [comment]
What's your username on Pypi? @Kronopt @tdmalone

**Comment by Kronopt** [comment]
[Kronopt](https://pypi.org/user/Kronopt/) (just created it)

**Comment by Naramsim** [comment]
I added you as a maintainer :smile: 

You should be able to push new versions. 

I already pushed this version. I also changed the readme and refactored the project with the new name.

I noticed that I cannot generate the docs on Windows. Can you take a look on that? If they generate well on your machine you can deploy them with the `npm` script that I#ve added. Take a look at the new `package.json`

**Comment by Naramsim** [comment]
@Kronopt feel free to decide for a pokemon and put it in the readme 😃 

Similarly to what we have done in:

- https://img.shields.io/pypi/pyversions/pokepy.svg
- https://github.com/PokeAPI/pokeapi-js-wrapper

**Comment by Kronopt** [comment]
Nice!

> I already pushed this version. I also changed the readme and refactored the project with the new name.

I had already done that, I just haven't pushed my fork to the pokeAPI/pokepy repo yet...

> I noticed that I cannot generate the docs on Windows. Can you take a look on that?

I'll see what I can do

> feel free to decide for a pokemon and put it in the readme 😃

Ok!

**Comment by Kronopt** [comment]
@Naramsim, I just need you to set the gh-pages branch as the source for the documentation.
And please, take a look at it, if you will 😃

**Comment by Naramsim** [comment]
http://pokeapi.github.io/pokepy/
