### ISSUE TITLE
Cache enabled clients produce error

### ISSUE THREAD

**Issue by lianne-hufkens** [PokeAPI/pokepy#31]
Following the example code for caching as described in the docs produces an typeError.

Both `client_mem_cache = pokepy.V2Client(cache='in_memory')` and `client_disk_cache = pokepy.V2Client(cache='in_disk', cache_location='/temp')` lead to:
```
~\Python36\lib\site-packages\beckett\clients.py", line 194, in __init__
    super(BaseClient, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes no parameters
```
The regular `client = pokepy.V2Client()` works just fine. Python version is 3.6.4, OS Windows 10.

**Comment by Kronopt** [comment]
I'm assuming you have version `0.4.0` from pypi.
Caching is only available on version `0.5.0`, which is still not on pypi (I'm still testing it out).

That's my bad for having already described the feature on the docs.

It will be out until the end of the week.
If you don't want to wait you can install it from github with the following command:
```bash
pip install git+https://github.com/PokeAPI/pykemon.git@master
```

**Comment by lianne-hufkens** [comment]
Thanks, I'll close the issue then.

**Comment by Kronopt** [comment]
@lianne-hufkens pykemon version 0.5.0 is now live.
You can now install it "normally":
```bash
pip install pokepy
```
