### ISSUE TITLE
get_pokemon() should not return a list.

### ISSUE THREAD

**Issue by lflimeira** [PokeAPI/pokepy#36]
First of all, greate job doing this wrapper. =)

When calling the get_pokemon() method, it should return the Pokemon object instead of a list of Pokemon objects, because it must never return more then one pokemon.

Example: 
```python
>>> import pokepy
>>> client = pokepy.V2Client()
>>> client.get_pokemon(14)
[<Pokemon - Kakuna>]
```
It's returnin `[<Pokemon - Kakuna>]` and sould return `<Pokemon - Kakuna>` instead.

**Comment by lflimeira** [comment]
If you allow me, I would like to solve this issue. Could you assign me?

**Comment by Kronopt** [comment]
Hey, thanks! :)

Yeah, that happens with other resources as well because that's the default behaviour of the beckett module.
It shouldn't be hard to implement. You just have to understand the beckett code.

Feel free to try it!
If you have any problems or questions leave a comment on this issue

**Comment by Kronopt** [comment]
I can't assign you...
But that's ok.
You can do it regardless

**Comment by lflimeira** [comment]
Thank you so much for your answer.

I'll see what I can do and as sun as possible I put some updates here. =)
