### ISSUE TITLE
Error on run of readMe example code

### ISSUE THREAD

**Issue by gabejchambers** [PokeAPI/pokepy#49]
When using 
`pokepy.V2Client()`
There is not the functions available listed in readMe or linked documentation. Cannot call 
`get_pokemon()` or `get_ability()` etc.

when run `print(dir(pokepy.V2Client()))` it DOES show access to get_pokemon(), etc. However, running `pokepy.V2Client().get_pokemon(14)` will cause program to run until force close, and IDE says "Instance of 'V2Client' has no 'get_pokemon' member"

**Comment by Kronopt** [comment]
Hi, gabejchambers.

I can't reproduce your problem.
Can you tell me your system, python version, installed python packages and IDE?
