### ISSUE TITLE
How to access `location_area_encounters` 

### ISSUE THREAD

**Issue by leonardohra** [PokeAPI/pokepy#53]
In the documentation I'd have to make a request to "https://pokeapi.co/api/v2/pokemon/ID/encounters"
If I use the client:
c = client.get_pokemon(10)
c.location_area_encounters

Shows me the url for the request ('https://pokeapi.co/api/v2/pokemon/10/encounters') but there's no method to access it. I didn't find other methods in the client related to that. I just wanted to be sure that the library doesn't do this before writing a method myself. Thanks!

**Comment by Naramsim** [comment]
Yeah, currently most of the wrappers lack this method. This is because the `/encounters` endpoint was added at a later stage. I guess the only way for you is to make an HTTP call to the endpoint returned by `location_area_encounters`

**Comment by leonardohra** [comment]
Thank you! I was afraid I would have to do that (I didn't want to have to do my own cache for the results of this method).

**Comment by Naramsim** [comment]
No need to cache it, do it only if you need a boost in speed.

**Comment by Kronopt** [comment]
There are many pokepy methods that return URLs for some properties.
Last year I began working on a feature to make those properties return actual data.
I haven't had much time to work on it lately, though...
