### ISSUE TITLE
An error has occurred.

### ISSUE THREAD

**Issue by hands8142** [PokeAPI/pokepy#72]
If you use this in Heroku, it will cause an error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'PokemonResource' object is not subscriptable
```

**Comment by Naramsim** [comment]
Can you post a simple example of code that triggers that error?

**Comment by hands8142** [comment]
https://github.com/hands8142/manyy_api/blob/938499ce8492cff3046a18bd1ba6d3b0d231c653/main.py#L206

I'm turning this around to Heroku. There is no error when I turn it to my local computer, but when I turn it to Heroku, an error occurs.

**Comment by Kronopt** [comment]
Can you specify both your environments?
Your local environment and heroku. Like, OS, python version, pokepy version, etc

**Comment by Kronopt** [comment]
Ah, I see your problem:

```python
poke = client.get_pokemon(pokename)[0]
```

should be 
```python
poke = client.get_pokemon(pokename)
```

hence the "not subscriptable" error.
You're probably using an older version of pokepy on heroku
