### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by DrAlta** [PokeAPI/pokepy#74]
```
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import pokepy
>>> mew = polepy.V2Client().get_pokemon('mew')
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    mew = polepy.V2Client().get_pokemon('mew')
NameError: name 'polepy' is not defined
>>> mew = pokepy.V2Client().get_pokemon('mew')
>>> mew
[<Pokemon - Mew>]
>>> mew.name
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    mew.name
AttributeError: 'list' object has no attribute 'name'
>>> 
```

**Comment by C-Garza** [comment]
It looks like you typed `polepy` instead of `pokepy`, is that your issue?
`mew = polepy.V2Client().get_pokemon('mew')`

**Comment by Kronopt** [comment]
Hello @DrAlta.
Pokepy doesn't explicitly support python 3.9 (yet), as @C-Garza mentioned.
Still I tried it myself (on python 3.9.2) and it did work correctly.
```python
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pokepy
>>> mew = pokepy.V2Client().get_pokemon('mew')
>>> mew.name
'mew'
```

Can you confirm you're using the latest version of pokepy?

**Comment by DrAlta** [comment]
Hi @Kronopt 
It looks like  "pip install pokepy" gave me version  0.4.0  I ended up just using
`def get_pokemon(pokemon):
    cachefile = "cache/pokemon/" + pokemon + ".json"
    if path.exists(cachefile):
        with open(cachefile, 'r') as pokefile:
            return(json.load(cachefile))
    else:
        r = requests.get('https://pokeapi.co/api/v2/pokemon/' + pokemon)
        if r.status_code == requests.codes.ok:
            with open(cachefile, 'w') as pokefile:
                pokefile.write(r.text)
            return(json.loads(r.text))
        else:
            return(False)`
If pokepy isn't any more useful than that as if it has any more features they aren't documented, so It's easier to just implement them myself than to reverse engineer how the API works.

**Comment by Kronopt** [comment]
Installing through `pip install pokepy` should have given you the latest version.

> If pokepy isn't any more useful than that as if it has any more features they aren't documented, so It's easier to just implement them myself than to reverse engineer how the API works.

If you think your code is better for your needs, that's cool! No hard feelings :)
You're always free to suggest new features, though!

And you don't need to reverse engineer pokepy to understand how it works, we have a [documentation for that](https://pokeapi.github.io/pokepy).
And you can always leave suggestions or other feedback if you think the documentation can be improved.
